# Generated by Django 4.2 on 2023-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(default=False, upload_to='media/audio'),
        ),
    ]
