# Generated by Django 4.2 on 2023-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_podcast_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='audio_file',
            new_name='audio_filess',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='content',
            new_name='contentss',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='date_published',
            new_name='date_publishedss',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='image',
            new_name='imagess',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='title',
            new_name='titless',
        ),
    ]
