# Generated by Django 4.2 on 2023-04-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_audio_file_podcast_audio_filess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_filess',
            field=models.FileField(upload_to='media/audio'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='imagess',
            field=models.ImageField(upload_to='media/blog'),
        ),
    ]
