# Generated by Django 4.2 on 2023-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitles', models.CharField(max_length=50)),
                ('ccontents', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/podcast')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/podcast')),
                ('date_times', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcast',
            },
        ),
    ]
