# Generated by Django 4.2 on 2023-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='picture',
            field=models.ImageField(upload_to='media/podcast'),
        ),
    ]
