# Generated by Django 4.2 on 2023-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_podcast_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(upload_to='media/podcast'),
        ),
    ]
