# Generated by Django 4.2 on 2023-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_podcast_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/event_pictures')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('display_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
