# Generated by Django 4.2 on 2023-04-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='media/productBooks')),
            ],
            options={
                'verbose_name': 'Productbooks',
                'verbose_name_plural': 'Productbooks',
            },
        ),
    ]
