# Generated by Django 4.2 on 2023-05-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed',
        ),
    ]
