# Generated by Django 4.2 on 2023-05-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_subscription_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Community',
        ),
    ]
