# Generated by Django 4.2 on 2023-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_subscription_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Communitys'},
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=False, upload_to='media/blog'),
        ),
    ]
