# Generated by Django 4.2 on 2023-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_community_options_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbooks',
            name='description',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='productbooks',
            name='price',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
