# Generated by Django 4.2 on 2023-05-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_productbooks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbooks',
            name='description',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productbooks',
            name='price',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
    ]
