# Generated by Django 4.2 on 2023-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_productbooks_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbooks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbooks',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmerchandise',
            name='ddescription',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productmerchandise',
            name='pprice',
            field=models.CharField(default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmerchandise',
            name='ttitle',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
